services:
  kafka-zookeeper:
    image: zookeeper:3.4.10
    container_name: kafka-zookeeper
    restart: always
    hostname: kafka-zookeeper
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    volumes:
      - kafka_zookeeper_data:/data
      - kafka_zookeeper_datalog:/datalog
    networks:
      - hadoop-network

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: kafka
    restart: always
    ports:
      - 9092:9092
    depends_on:
      - kafka-zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: kafka-zookeeper:2181
      KAFKA_CREATE_TOPICS: "test-topic:1:1,events:1:1,logs:1:1"
      KAFKA_LOG_RETENTION_HOURS: 24
    volumes:
      - kafka_data:/kafka
    networks:
      - hadoop-network

  kafka-manager:
    image: hlebalbau/kafka-manager:stable
    container_name: kafka-manager
    restart: always
    ports:
      - 9000:9000
    depends_on:
      - kafka
    environment:
      ZK_HOSTS: "kafka-zookeeper:2181"
      APPLICATION_SECRET: "random-secret"
    networks:
      - hadoop-network

volumes:
  kafka_zookeeper_data:
  kafka_zookeeper_datalog:
  kafka_data:

networks:
  hadoop-network:
    external: true