version: '3.8'

services:
  zoo1:
    image: zookeeper:3.4.10
    container_name: zoo1
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog
    networks:
      - hadoop-network

  hbase-master:
    image: bde2020/hbase-master:1.0.0-hbase1.2.6
    container_name: hbase-master
    restart: always
    hostname: hbase-master
    env_file:
      - ./hbase-distributed-local.env
    environment:
      SERVICE_PRECONDITION: "namenode:9000 datanode:9864 zoo1:2181"
    depends_on:
      - zoo1
    ports:
      - 16010:16010
    networks:
      - hadoop-network

  hbase-region:
    image: bde2020/hbase-regionserver:1.0.0-hbase1.2.6
    container_name: hbase-regionserver
    restart: always
    hostname: hbase-regionserver
    env_file:
      - ./hbase-distributed-local.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-regionserver
      SERVICE_PRECONDITION: "namenode:9000 datanode:9864 zoo1:2181 hbase-master:16010"
    depends_on:
      - zoo1
      - hbase-master
    ports:
      - 16030:16030
    networks:
      - hadoop-network

volumes:
  zookeeper_data:
  zookeeper_datalog:

networks:
  hadoop-network:
    external: true