# Base Hadoop services - always needed
services:
  namenode:
    image: apache/hadoop:3.4.1
    container_name: namenode
    restart: always
    hostname: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop_namenode:/opt/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - ENSURE_NAMENODE_DIR=/opt/hadoop/dfs/name
    command: ["hdfs", "namenode"]
    networks:
      - hadoop-network
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:9870/"]
#      interval: 30s
#      timeout: 10s
#      retries: 3

  datanode:
    image: apache/hadoop:3.4.1
    container_name: datanode
    restart: always
    hostname: datanode
    volumes:
      - hadoop_datanode:/opt/hadoop/dfs/data
    environment:
      - ENSURE_DATANODE_DIR=/opt/hadoop/dfs/data
    command: ["hdfs", "datanode"]
    depends_on:
      namenode:
        condition: service_healthy
    networks:
      - hadoop-network

  resourcemanager:
    image: apache/hadoop:3.4.1
    container_name: resourcemanager
    restart: always
    hostname: resourcemanager
    ports:
      - "8088:8088"
    environment:
      - ENSURE_RESOURCEMANAGER_DIR=/opt/hadoop/logs/yarn
    command: ["yarn", "resourcemanager"]
    depends_on:
      namenode:
        condition: service_healthy
    networks:
      - hadoop-network

  nodemanager:
    image: apache/hadoop:3.4.1
    container_name: nodemanager
    restart: always
    hostname: nodemanager
    environment:
      - ENSURE_NODEMANAGER_DIR=/opt/hadoop/logs/yarn
    command: ["yarn", "nodemanager"]
    depends_on:
      - resourcemanager
    networks:
      - hadoop-network

  historyserver:
    image: apache/hadoop:3.4.1
    container_name: historyserver
    restart: always
    hostname: historyserver
    volumes:
      - hadoop_historyserver:/opt/hadoop/logs/yarn
    ports:
      - "8188:8188"
    command: ["yarn", "timelineservice"]
    depends_on:
      - resourcemanager
    networks:
      - hadoop-network

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:

networks:
  hadoop-network:
    driver: bridge